"""Linking

Revision ID: 2f148711117a
Revises: c50e7920fbfa
Create Date: 2025-05-16 22:58:30.811826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '2f148711117a'
down_revision: Union[str, None] = 'c50e7920fbfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_asset_type_config_id', table_name='asset_type_config')
    op.drop_table('asset_type_config')
    op.add_column('assets', sa.Column('linked_assets', sqlite.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'linked_assets')
    op.create_table('asset_type_config',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('type_name', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type_name')
    )
    op.create_index('ix_asset_type_config_id', 'asset_type_config', ['id'], unique=False)
    # ### end Alembic commands ###
