"""Ensure custom_fields exists in Asset table

Revision ID: c50e7920fbfa
Revises: 5a9411fb6de0
Create Date: 2025-05-12 23:10:17.549615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'c50e7920fbfa'
down_revision: Union[str, None] = '5a9411fb6de0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('custom_fields', sqlite.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'custom_fields')
    # ### end Alembic commands ###
